language: java
jdk: oraclejdk11

before_install:
  - chmod +x gradlew

script: >-
  ./config/travis/run-checks.sh &&
  ./gradlew clean checkstyleMain checkstyleTest asciidoctor coverage coveralls jacocoTestReport

deploy:
  skip_cleanup: true
  provider: script
  script: ./config/travis/deploy_github_pages.sh
  on:
    branch: master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
